### ISSUE TITLE
Use label service.kubernetes.io/service-proxy-name to select nfproxy

### ISSUE THREAD

**Issue by uablrek** [sbezverk/nfproxy#49]
## Use label service.kubernetes.io/service-proxy-name to select nfproxy

There is a way to select a proxier other than `kube-proxy` by defining a label in the service manifest;

```
apiVersion: v1
kind: Service
metadata:
  name: mserver-nfproxy
  labels:
    service.kubernetes.io/service-proxy-name: nfproxy
spec:
  selector:
    app: mserver
  ports:
  - port: 5001
```

If `nfproxy` filters it's services by this label it can co-exist with `kube-proxy` and handle services with special needs.

This would probably also make users less reluctant to use `nfproxy` since the standard `kube-proxy` would not be replaced and K8s installation will be "normal". `nfproxy` may then be added separately to any installed K8s cluster.

A new options may be added to `nfproxy`;

```
--service-proxy-name <name> - Let nfproxy only handle services with this label
```

### Implementation

`nfproxy` should use a filter to select only the relevant services. Here is how it is done in `kube-proxy`;

https://github.com/kubernetes/kubernetes/blob/84dc7046797aad80f258b6740a98e79199c8bb4d/cmd/kube-proxy/app/server.go#L667-L684

The `kube-proxy` ignores all services having the `.kubernetes.io/service-proxy-name` label. `nfproxy` skall only select services having this label set to the name defined by the `--service-proxy-name` option.

I think this function shall be added somewhere here;

https://github.com/sbezverk/nfproxy/blob/9938c27e48637c217a565da169134c2d967ba972/cmd/nfproxy.go#L141

At the same time a filter can be added to *not* watch "headless" services, same as `kube-proxy`.
